sudo: required
services:
- docker

branches: 
  only: 
    - travis

env:
  global:
  - PLUGIN_NAME=ldsplugin
  - secure: FVV1oDLePTeQ0k/Eme3K85Fi/HJnI6H9PJowACfFUWeJOiKAaEtnbBV+Iww5jM1NQu3mI7q6H8aVZfQGhfIT0f9TSkgPrFPDWJBGnLLw1P+UCOD/feW945q5I8h/U8W6CfRA5m2HBwqS6C6mKvtFMoTARKwS0Ra1lJU12j6YunLkSoozFqpBoUC3dAKIVDMu2Gf9HvGsh8X3cI2A+B2UsJFngnk4HJl5PeBbzwMNezdnRw/KBqV5bAyiUa8qibHiAKZi++CBsGYyLb9gvGGELn8Z0LbYftmS9lj+bZiolXvNMbGwTHaKiSP5zo8qCeD5qy43clcgATGLdc594Ip7p6bgRIflxx+hC9LgC4DyRSoQOh1l7FBO0TUcJtqZlH31frOylSELEMuZkvTxpR5R9gGCkgTb4UUDZ2Fm7134G+f+gM5kSWuejKHY8PfBbba0reFfA4Dzvk24SyONrrruu1L53cR6rc0A+8vvfJ1BWR16Y9inUjr0Kdcb/kz9iEt/dpGKywBB98tJoASk63bdWkkp6f5Vvx3E0Tos5k2InwdiBN1WTzalnMYoPdPiXKk6TgfubhtJhO80aVaFUeTs8V40447QTNRUWz5jqJtF53M78JDFN6LXwvd+rKe5zfWJu19tkV1Cjb9sPmz1Nay9PvJ07qniL/uAr8RXXxSrK1Q=
  matrix:
  - QGIS_VERSION_TAG=release
  - QGIS_VERSION_TAG=master_2
  #- QGIS_VERSION_TAG=master
#matrix:
  #allow_failures:
  #- env: QGIS_VERSION_TAG=master
before_install:
  - docker pull boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG}
  - docker tag boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG} qgis-testing-environment
install:
    - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-testing-environment
    - sleep 10
    - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
    - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory /root/.qgis2/python/plugins/${PLUGIN_NAME}"
script:
    - docker-compose exec qgis-testing-environment sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.tests.run_tests"
