sudo: false
services:
- docker
env:
  global:
  - PLUGIN_NAME=linz-data-importer
  - IMAGE=elpaso/qgis-testing-environment
  - secure: Hr1mJ1gHIx8PmHCGq/6GfxwNWeS2q4tSCG5jjdzlrP+mX/slVYEPwz4nALUI+s24iRd6Q/dZxaYIPUPk4pyEuu0/xF5kQPBF4qTfnF8H1b7CUdN9clEcCSLTy3wbqKgG+iPC1wEezM9TvWnBUsAlthc23ssP1ldfHr+0SpGJ980EqXzmT4Jimwb/20jWZQ4fvNwLPRFpPuKJPSmEzhTd6VvwLYFWfUPE7ylvaA9KlU3tEZom8kC2enGKUR+N6ayoeGBW9IseTF/N44HNjmTSPWDHPapLroXXVfcq5oTpYFuA57nsiZpBh1NypcfroeEt8ZlgnJ2hjY6ryZJv+HoV9d70eMgvk9E1gt2Z/eA/2aH6ZzCHz9iiE5GeFBgAO7RXJ9XdMPwaarsf7VTf/HLtkDEND4UHH/G7eNXBRh5G6uyhxf+PqVZUWO4wKXtY6Bw+SFeCMtlMnBDkFv9Y41jOAYRAtFIo74hera0CCFcHU9FNG7aJXuhBHQ6X+VTX3Sx/yO4bjRxl/kb8VtSIQtjNdo7Uclil/Sxczv597vr79ESEfj4KJ0xHAFGKizDD6Hu+28Bl9rcqqfLbvO53Wmgc/IzYkhK0ql13Kl2tuqYq7biRFcwpVl4TFyDI+4eUcqK+0QUmmiPStayvG7ilPz31J8B+ZBTrCxixYU6ADXEXchQ=
  - secure: Ut1EQoRGqhaoFhm4viv6VfL1QYtQAokreI/F3DvadAN3Pxa1IIh/eJcAJeKtm+/VCGF92MuUktf2wkZx8gYl4q2Jf4157Ta5SA8JblMEVPf2r+jUvdJIeDd5/2GAwjVhiLeFZTEC1MW4cQmzzyRZWM+kMzeklfjhVy8MnM/j2v7Bi++SfT7hMydchaJA50qeDkdXsjoieCCrq2c8Xh/cojagRZCCTIGzMx3sSh+4mZvp3jVarGghgeGVddY5JzK2yB1HwZOIgBvIp8f8mjNBVPVyKwFphm7sswErOv8b6+h0Lhnmu8NRkDangm2oAeW7U2OdA7TOzokb9NlR25UUkHOLMov77mPWQmDSy6m3QPraFr1eIrIfqYWoUc6Qfv61iGI0xyQXNVYoUXJBBsnSBbxL/zBdyFJdllFIWcFH9rXZWRqzHfZKK32+3ANdsukUV0aexlNxPtIGvrMTx5esTBRZ69Ow0j1h8hgBH83IhX+ImNTequOPXjlr03ceCAF67vUMWZ1pdtjSH5pBB8r5/Sk6pRPR+LPlpfGfcaQ7JXR3EkDU+wpp11SXRJW9BAb2SAg7EAtQwhgfxA30W6FF7N+4/5KuOjPewrIr+dIRt5ZCH3uJifQ2eDRcWkUKFchvYFO6jWdJOQTm891jqW5MPHc3t4D0iexyU5N2TNUPfoo=
  - secure: SCQa0WiXA6Z1TSkMq8FEow5u78wB5F9R5OE8A/Dq4tc9zLo7SmoB049/HMXJJ7r2qb5CbcPnZcr3iS8cARKyjhnDy+D0/IoD3lae3BYiQkkCJQSToEnFYL4+UmNgvLmnibPC3PM80RtSzWGgR5aEdw4PSVOuKBelW6ga6X5XoOGvjypiu72GkaoRu9v2h5BgEaIMkimXjkiRjsG5L+gdJbsqDzv9GSoCSQvoQXhT+6HXwmEB6skCQ0EK9i2AcIjLa8HZGqe+nnPgm9UK75AVdPhGpmSWawvEnokkHsRQ3AjzcHOnmTavEO77RZsR8YwgOekIBVVZ7KJicfAFyic28McSP+ci2TkA5rsNIggRI29cAiwuXgan7GxOShcw+5qbOppgFR5U50tz80/Khv1WrIq/UE7SNYLA1buWFaQg2xDzuo9/+Rk688Ohr1CCPTBLEvmsyzplMSAKQWKbsw2sqrZYMIZRXTSmW7Jl48fPGXWpwje5rvcKOAd8F8BHXCxC07uqDjWFY2BqsZJ8dkMOrtsMoHKJmdjyQ/Rg9tsWJUf4tYniP6WwW5OaXHk0j4/trqsHVPGvSMMwc9hnYkw0MOpXCJjeiWIUW0Q2DhPakH+pKt4Q8HbeXtqhO9TvruYDOc4rxqWDI4zAyQEMWxnTjhKs8u+Sre9eziFng8DoMOc=
  matrix:
  - QGIS_VERSION_TAG=master
language: python
python:
- '3.6'
branches:
  only:
  - master_qgis3
before_install:
- docker pull ${IMAGE}:${QGIS_VERSION_TAG}
install:
- docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory
  -e LDI_LINZ_KEY -e LDI_MFE_KEY -e LDI_NZDF_KEY -e DISPLAY=:99 ${IMAGE}:${QGIS_VERSION_TAG}
- sleep 10
- docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory /root/.local/share/QGIS/QGIS3/profiles/default/${PLUGIN_NAME}"
script:
- docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.tests.run_tests.run_test_modules"
