services:
    - docker

branches: 
  only: 
    - travis

env:
  global:
      - PLUGIN_NAME=ldsplugin
      - secure:bCE+mOhqZTYc8LM6HZdtIjOeuDFYnVtuVrFT5j+OcUMnESVZvJDkyjqTiVTgtcOT/cK6Ado8CvZTecxHIcy9VIGlMZSYLorfbG6RLzfHsRuurnhVjM88ik760CptwpcD/SMfWhl8P1scfG3Km4hCqdzumPGBk1jhMYdzRKe9G5S6YxPgPWjBmXcvM/zit0lafWinciffVmiq/gknv2E3tQvdLFrQhb4Uz93AvH4YH2mzTK8ahcbIKlym2Nm21K7Qo8H+6lb2hcK/dXOAJbdgev7eVYZdjE1oLBB10NAbhQl+D9cGvZKRII8qPcnTzrNg6cwl61hPiwBoQ9VVzKxNQvpRvSzXAZojFHWtK3uxacc8stymALBp+RqGdAr0C0U27f2Vk26p+u+CDczXG4oSGAOjWk2BMiJW84A+HHulskZ9D/usy/xDLkY/Km6jV8Qdz51iQo47KUIST5lK9DtWb31p0xI0xZzSi2sJq4m+KTBrvc8hCXTJE1OrFwF0A0U78PEhg9jJC7cVzO4bQpIsFA5dw2tbCi05VJcwCbh0mOy6odeyZ7V5uagnG411hGWKIPiO+H9/kLdF+qs2MrjdPjeGx6rfAZUevZfp7o3etSVimOdwBVkeIibojvujvjbjw45xRCnR7lVT6K1phMYvwWD4bSl9eZQ5B+6QS12c5Jk=

  matrix:
    #  - QGIS_VERSION_TAG=release PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
      - QGIS_VERSION_TAG=master_2 PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
    # - QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip

before_install:
    - docker pull boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG}
    - docker tag boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG} qgis-testing-environment
install:
    - docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e LDS_API -e DISPLAY=:99 qgis-testing-environment 
    - sleep 10
    - docker exec -it qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
    - docker exec -it qgis-testing-environment sh -c "ln -s /tests_directory /root/.qgis2/python/plugins/${PLUGIN_NAME}"
    - docker exec -it qgis-testing-environment sh -c "pip install pyproj"

script:
    - docker exec -it qgis-testing-environment sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.tests.run_tests.run_test_modules"
